### ISSUE TITLE
i can't login in it ?

### ISSUE THREAD

**Issue by alidz1982** [goosehub/bigworld#1]

**Comment by goosehub** [comment]
Hello, dev here. I'm not seeing this issue. Can you provide more information. What happens when you try to log in? Are there any error messages? Are you able to create a new account and use that to log in and log out?

Also, are you a developer hoping to create your own instance of this project or just a user?

**Comment by alidz1982** [comment]
i test it in windows 10 + xampp .. i find my account in mysql -but  when i try login nothing happen

**Comment by goosehub** [comment]
Did you create your account by registering on your dev website, or did you manually insert it into the database?
